### ISSUE TITLE
ai_fn response value returning title/type dict when using 3.5-turbo

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/marvin#121] opened 2023-03-31 15:34 UTC
```from marvin import ai_fn

@ai_fn
def watering_schedule_from_plant(plant_name: str) -> str:
    """takes a plant name and returns watering instructions"""
    
instruction = watering_schedule_from_plant(plant_name="ficus")

print(instruction)
```

returns 

`{"title": "Model", "type": "string"}`

**Comment by discdiver** [comment] 2023-03-31 15:43
That fixed it for me. We should update the docs with that tip, perhaps

# ['Water your ficus once a week in moderate sunlight.']

**Comment by zzstoatzz** [comment] 2023-04-04 22:00
closing as duplicate of #118

**Closed by zzstoatzz** 2023-04-04 22:00 UTC

**Comment by jlowin** [comment] 2023-04-08 00:19
I believe this issue has been solved with recent changes to the format prompts
