### ISSUE TITLE
[Azure OpenAI] Error when deployment name != model name

### ISSUE THREAD

**Issue by pietz** [PrefectHQ/marvin#842] opened 2024-02-12 17:58 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Currently when using marvin with Azure OpenAI, the deployment name in Azure has to match the model name in Azure. Othwise it throws this error:

`KeyError: 'Could not automatically map gpt-35 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'`

A bit more context: Azure OpenAI introduces the term "deployment name" that can be any string you define. "model name" is the name of the actual model from OpenAI that you're using. Many people treat it as best practice naming your deployment after your selected model, but you absolutely don't have to.

Marvin throws the error above in case the two don't fully match.

### Reproduction

```python3
Create a model deployment in Azure OpenAI. Select a model like "gpt-35-turbo" and give the deployment any other name than that.
```

### Versions

```Text
2.1.4
```

**Comment by Fakamoto** [comment] 2024-02-21 18:10
I have the exact same error, did you find a solution?

I think the problem is in marvin/settings.py

```
class ChatCompletionSettings(MarvinSettings):
    model_config = SettingsConfigDict(env_prefix="marvin_chat_completions_")
    model: str = Field(
        description="The default chat model to use.", default="gpt-4-1106-preview"
    )

    temperature: float = Field(description="The default temperature to use.", default=1)

    @property
    def encoder(self):
        import tiktoken

        return tiktoken.encoding_for_model(self.model).encode
```

basically there is no tiktoken encoder for the name of your deployment. They need to change this. But have you come to a workaround? I tried manually writing `return tiktoken.encoding_for_model("gpt-4-1106-preview").encode` but it still fails

**Comment by zzstoatzz** [comment] 2024-03-07 19:03
v2.1.6 has been released with that change - let us know if you encounter any more issues here

**Closed by zzstoatzz** 2024-03-07 19:03 UTC
Labels: bug
